version: '3'

volumes:
  authv:
  storev:

networks:
  authdbnet:
  storedbnet:
  bcnet:

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", authenticationDB]
      timeout: 10s
      retries: 10
    volumes:
      - authv:/var/lib/mysql
    networks:
      - authdbnet
    ports:
      - 3309:3306
  authentication:
    image: auth
    environment:
      - DBHOST=authenticationDB
    ports:
      - 5000:5000
    networks:
      - authdbnet
    depends_on:
      authenticationDB:
        condition: service_healthy
  storeDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", storeDB ]
      timeout: 10s
      retries: 10
    volumes:
      - storev:/var/lib/mysql
    networks:
      - storedbnet
    ports:
      - 3307:3306
  store:
    image: store
    environment:
      - IP_ADDR=statistics
      - DBHOST=storeDB
      - DBPW=root
      - DBUSER=root
      - BC_HOST=bc_simulator
    ports:
      - 5001:5000
    networks:
      - storedbnet
      - bcnet
    depends_on:
      storeDB:
        condition: service_healthy
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - storedbnet
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - storedbnet
  statistics:
    image: stats
    environment:
      - IP_ADDR=storeDB
      - DBHOST=storeDB
      - SPARK_HOST=spark-master
      - ENABLE_INIT_DAEMON=false
    networks:
      - storedbnet
    depends_on:
      storeDB:
        condition: service_healthy
      spark-master:
        condition: service_started
      spark-worker-1:
        condition: service_started
  bc_simulator:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    networks:
      - bcnet

