export var classes = [
    {
        "student": "ana1",
        "teacher": "n4",
        "subject": "Mathematics",
        "link": "1",
        "student_description": "Hocu da ucim",
        "double": true,
        "status": 1,
        "start": "2024-01-01T11:00:00",
        "end": "2024-01-01T12:00:00",
        "grade_s": 3,
        "comment_s": "Bas nice",
        "grade_t": 4,
        "comment_t": "Kul"
    },
    {
        "student": "ana2",
        "teacher": "n4",
        "subject": "Programming",
        "link": "2",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-01-01T12:00:00",
        "end": "2024-01-01T14:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana3",
        "teacher": "n4",
        "subject": "Programming",
        "link": "3",
        "student_description": "Hocu da ucim",
        "double": true,
        "status": 1,
        "start": "2024-01-02T15:00:00",
        "end": "2024-01-02T16:00:00",
        "grade_s": 5,
        "comment_s": "YEY",
        "grade_t": 5,
        "comment_t": "Not bad"
    },
    {
        "student": "ana1",
        "teacher": "n2",
        "subject": "Latin",
        "link": "4",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-01-02T10:00:00",
        "end": "2024-01-02T11:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana2",
        "teacher": "n2",
        "subject": "Programming",
        "link": "5",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-01-02T14:00:00",
        "end": "2024-01-02T16:00:00",
        "grade_s": 2,
        "comment_s": "ne znam ja ovo",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana1",
        "teacher": "n3",
        "subject": "Spanish",
        "link": "6",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-01-03T13:00:00",
        "end": "2024-01-03T15:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": 5,
        "comment_t": "Hola"
    },
    {
        "student": "ana2",
        "teacher": "n3",
        "subject": "German",
        "link": "7",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-01-03T10:00:00",
        "end": "2024-01-03T11:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": 4,
        "comment_t": "KEKEKEKKEK"
    },
    {
        "student": "ana3",
        "teacher": "n3",
        "subject": "Italian",
        "link": "8",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-01-04T12:00:00",
        "end": "2024-01-04T13:00:00",
        "grade_s": 4,
        "comment_s": "dobar je",
        "grade_t": 2,
        "comment_t": "ciao"
    },
    {
        "student": "ana1",
        "teacher": "n1",
        "subject": "Mathematics",
        "link": "9",
        "student_description": "Hocu da ucim",
        "double": true,
        "status": 1,
        "start": "2024-01-05T10:00:00",
        "end": "2024-01-05T12:00:00",
        "grade_s": 1,
        "comment_s": "bad bad BEANS",
        "grade_t": 3,
        "comment_t": "I love apples"
    },
    {
        "student": "ana2",
        "teacher": "n1",
        "subject": "Physics",
        "link": "10",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-01-06T15:00:00",
        "end": "2024-01-06T17:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": "",
    },
    {
        "student": "ana3",
        "teacher": "n1",
        "subject": "Mathematics",
        "link": "11",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-01-07T13:00:00",
        "end": "2024-01-07T14:00:00",
        "grade_s": 4,
        "comment_s": "Uh ah",
        "grade_t": 2,
        "comment_t": "C C C"
    },
    //------------------------------------
    {
        "student": "ana2",
        "teacher": "n4",
        "subject": "Chemistry",
        "link": "13",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-01-03T08:00:00",
        "end": "2024-01-03T09:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana3",
        "teacher": "n4",
        "subject": "Chemistry",
        "link": "14",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-01-04T10:00:00",
        "end": "2024-01-04T11:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana4",
        "teacher": "n4",
        "subject": "Programming",
        "link": "15",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-01-05T10:00:00",
        "end": "2024-01-05T12:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana4",
        "teacher": "n1",
        "subject": "Physics",
        "link": "16",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-01-06T09:00:00",
        "end": "2024-01-06T10:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana2",
        "teacher": "n1",
        "subject": "Physics",
        "link": "17",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-01-03T12:00:00",
        "end": "2024-01-03T14:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana2",
        "teacher": "n1",
        "subject": "Mathematics",
        "link": "18",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-01-01T09:00:00",
        "end": "2024-01-01T11:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana1",
        "teacher": "n2",
        "subject": "Serbian",
        "link": "19",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-01-02T09:00:00",
        "end": "2024-01-02T10:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana2",
        "teacher": "n2",
        "subject": "Programming",
        "link": "20",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-01-08T14:00:00",
        "end": "2024-01-08T15:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana1",
        "teacher": "n3",
        "subject": "German",
        "link": "21",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": -1,
        "start": "2024-01-02T13:00:00",
        "end": "2024-01-02T14:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": "Nemam kad"
    },
    {
        "student": "ana2",
        "teacher": "n3",
        "subject": "Italian",
        "link": "22",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": -1,
        "start": "2024-01-03T08:00:00",
        "end": "2024-01-03T09:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": "Teza pricica"
    },
    {
        "student": "ana3",
        "teacher": "n3",
        "subject": "German",
        "link": "23",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-01-04T13:00:00",
        "end": "2024-01-04T15:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana1",
        "teacher": "n4",
        "subject": "Informatics",
        "link": "24",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": -1,
        "start": "2024-01-05T08:00:00",
        "end": "2024-01-05T09:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": "Ne stizem"
    },
    {
        "student": "ana2",
        "teacher": "n4",
        "subject": "Programming",
        "link": "25",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": -1,
        "start": "2024-01-05T08:00:00",
        "end": "2024-01-05T09:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ":<<"
    },
    {
        "student": "ana3",
        "teacher": "n2",
        "subject": "",
        "link": "26",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": -1,
        "start": "2024-01-05T08:00:00",
        "end": "2024-01-05T09:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": "*Auf*"
    },
    {
        "student": "ana1",
        "teacher": "n4",
        "subject": "Mathematics",
        "link": "27",
        "student_description": "Hocu da ucim",
        "double": true,
        "status": 1,
        "start": "2024-03-01T09:00:00",
        "end": "2024-03-01T10:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana2",
        "teacher": "n4",
        "subject": "Programming",
        "link": "28",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-03-01T11:00:00",
        "end": "2024-03-01T12:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    //--------------------------- 
    //ovde su casovi za februar koji treba da budu oko datuma odbrane, 
    //rasporedjeni nekako i rastrkani po satima
    //sredi to kad saznas kad je odbrana
    { //n1
        "student": "ana3",
        "teacher": "n1",
        "subject": "Physics",
        "link": "29",
        "student_description": "Hocu da ucim",
        "double": true,
        "status": 1,
        "start": "2024-02-19T10:00:00",
        "end": "2024-02-19T12:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana2",
        "teacher": "n1",
        "subject": "Italian",
        "link": "30",
        "student_description": "Hocu da ucim",
        "double": true,
        "status": 1,
        "start": "2024-02-19T12:00:00",
        "end": "2024-02-19T14:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana4",
        "teacher": "n1",
        "subject": "Biology",
        "link": "31",
        "student_description": "Hocu da ucim",
        "double": true,
        "status": 0,
        "start": "2024-02-21T11:00:00",
        "end": "2024-02-21T13:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana0",
        "teacher": "n1",
        "subject": "Physics",
        "link": "32",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-02-21T15:00:00",
        "end": "2024-02-21T16:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    }, //n2
    {
        "student": "ana0",
        "teacher": "n2",
        "subject": "Informatics",
        "link": "33",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-02-20T15:00:00",
        "end": "2024-02-20T16:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana1",
        "teacher": "n2",
        "subject": "Latin",
        "link": "34",
        "student_description": "Hocu da ucim",
        "double": true,
        "status": 1,
        "start": "2024-02-23T12:00:00",
        "end": "2024-02-23T14:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana4",
        "teacher": "n2",
        "subject": "Geography",
        "link": "35",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-02-21T13:00:00",
        "end": "2024-02-21T14:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana0",
        "teacher": "n2",
        "subject": "Italian",
        "link": "36",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-02-21T14:00:00",
        "end": "2024-02-21T15:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    }, //n4
    {
        "student": "ana0",
        "teacher": "n4",
        "subject": "History",
        "link": "37",
        "student_description": "Hocu da ucim",
        "double": true,
        "status": 1,
        "start": "2024-02-20T09:00:00",
        "end": "2024-02-20T11:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana0",
        "teacher": "n4",
        "subject": "German",
        "link": "38",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 1,
        "start": "2024-02-22T10:00:00",
        "end": "2024-02-22T11:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana3",
        "teacher": "n4",
        "subject": "Informatics",
        "link": "39",
        "student_description": "Hocu da ucim",
        "double": false,
        "status": 0,
        "start": "2024-02-21T13:00:00",
        "end": "2024-02-21T14:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    },
    {
        "student": "ana2",
        "teacher": "n4",
        "subject": "Chemistry",
        "link": "40",
        "student_description": "Hocu da ucim",
        "double": true,
        "status": 0,
        "start": "2024-02-21T15:00:00",
        "end": "2024-02-21T17:00:00",
        "grade_s": -1,
        "comment_s": "",
        "grade_t": -1,
        "comment_t": ""
    }
];
