export var admin = [
    {
        "username": "admin",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "ana",
        "surname": "zoric",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "female",
        "type": "admin"
    }
];
export var students = [
    {
        "username": "ana0",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "ana0",
        "surname": "zoric0",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "female",
        "address": "Tome Rosandica",
        "email": "ana.zoric@gmail.com",
        "phone": "0603144447",
        "school_type": "Primary school",
        "year": 1,
        "type": "student",
        "avg_grade": 3,
        "num_grades": 2
    },
    {
        "username": "ana1",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "ana1",
        "surname": "zoric1",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "female",
        "address": "Tome Rosandica",
        "email": "a1@gmail.com",
        "phone": "0603144447",
        "school_type": "Grammar school",
        "year": 2,
        "type": "student",
        "avg_grade": 2.5,
        "num_grades": 2
    },
    {
        "username": "ana2",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "ana2",
        "surname": "zoric2",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "female",
        "address": "Tome Rosandica",
        "email": "a2@gmail.com",
        "phone": "0603144447",
        "school_type": "Grammar school",
        "year": 3,
        "type": "student",
        "avg_grade": 4.9,
        "num_grades": 9
    },
    {
        "username": "ana3",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "ana3",
        "surname": "zoric3",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "female",
        "address": "Tome Rosandica",
        "email": "a3@gmail.com",
        "phone": "0603144447",
        "school_type": "Grammar school",
        "year": 4,
        "type": "student",
        "avg_grade": 4.3,
        "num_grades": 12
    },
    {
        "username": "ana4",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "ana4",
        "surname": "zoric4",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "male",
        "address": "Tome Rosandica",
        "email": "a4@gmail.com",
        "phone": "0603144447",
        "school_type": "Primary school",
        "year": 5,
        "type": "student",
        "avg_grade": 4.2,
        "num_grades": 6
    },
    {
        "username": "ana5",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "ana5",
        "surname": "zoric5",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "female",
        "address": "Tome Rosandica",
        "email": "a5@gmail.com",
        "phone": "0603144447",
        "school_type": "Grammar school",
        "year": 2,
        "type": "student",
        "avg_grade": 4,
        "num_grades": 8
    },
    {
        "username": "ana6",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "ana6",
        "surname": "zoric6",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "male",
        "address": "Tome Rosandica",
        "email": "a6@gmail.com",
        "phone": "0603144447",
        "school_type": "Primary school",
        "year": 8,
        "type": "student",
        "avg_grade": 5,
        "num_grades": 7
    }
];
export var teachers = [
    {
        "username": "n1",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "Marko1",
        "surname": "Ilic1",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "male",
        "address": "Tome Rosandica",
        "email": "t1@gmail.com",
        "phone": "0603144447",
        "ages": ["1-4", "5-8"],
        "subjects": ["Mathematics", "Physics", "Chemistry", "Serbian", "Italian", "Spanish", "Biology", "Geography"],
        "additional_subject": "",
        "heard_from": "ne secam se",
        "accepted": 1,
        "type": "teacher",
        "avg_grade": 4,
        "num_grades": 10
    },
    {
        "username": "n2",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "Marko3",
        "surname": "Ilic3",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "female",
        "address": "Tome Rosandica",
        "email": "t3@gmail.com",
        "phone": "0603144447",
        "ages": ["9-12"],
        "subjects": ["Physics", "Informatics", "Programming", "Serbian", "Italian", "French", "Latin", "History", "Geography"],
        "additional_subject": "Music",
        "heard_from": "ne secam se",
        "accepted": 1,
        "type": "teacher",
        "avg_grade": 3.5,
        "num_grades": 12
    },
    {
        "username": "n3",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "Marko2",
        "surname": "Ilic2",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "female",
        "address": "Tome Rosandica",
        "email": "t2@gmail.com",
        "phone": "0603144447",
        "ages": ["1-4"],
        "subjects": ["Programming", "English", "German", "Italian", "Spanish", "Serbian"],
        "additional_subject": "Cocktails",
        "heard_from": "ne secam se",
        "accepted": 0,
        "type": "teacher",
        "avg_grade": 4.2,
        "num_grades": 8
    },
    {
        "username": "n4",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "Marko4",
        "surname": "Ilic4",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "female",
        "address": "Tome Rosandica",
        "email": "t4@gmail.com",
        "phone": "0603144447",
        "ages": ["5-8", "9-12"],
        "subjects": ["Mathematics", "Chemistry", "Informatics", "Programming", "German", "Spanish", "Biology", "History", "World around us"],
        "additional_subject": "",
        "heard_from": "ne secam se",
        "accepted": 1,
        "type": "teacher",
        "avg_grade": 5,
        "num_grades": 3
    },
    {
        "username": "n5",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "Stefan",
        "surname": "Stefanovic",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "male",
        "address": "Tome Rosandica",
        "email": "t5@gmail.com",
        "phone": "0603144447",
        "ages": ["1-4", "5-8", "9-12"],
        "subjects": ["Chemistry", "Serbian", "English", "German", "Latin", "Biology"],
        "additional_subject": "",
        "heard_from": "ne secam se",
        "accepted": 0,
        "type": "teacher",
        "avg_grade": 4.9,
        "num_grades": 18
    },
    {
        "username": "n6",
        "password": "$argon2id$v=19$m=6000,t=3,p=1$SWcwbGxEZEVkYkNBaUVNQQ$7rgDeJaWI/7YfFQUb9E5Yy7YJiyklCHoyuCC0YbzHEc",
        "name": "Luka",
        "surname": "Lukic",
        "sec_question": "koliko imam godina",
        "sec_answer": "22",
        "gender": "female",
        "address": "Tome Rosandica",
        "email": "t6@gmail.com",
        "phone": "0603144447",
        "ages": ["5-8", "9-12"],
        "subjects": ["Informatics", "English", "French", "History", "World around us"],
        "additional_subject": "Art",
        "heard_from": "ne secam se",
        "accepted": 1,
        "type": "teacher",
        "avg_grade": 5,
        "num_grades": 3
    }
]