"""empty message

Revision ID: e93f3239d499
Revises: 7b64a5c3aec6
Create Date: 2023-07-12 19:02:29.964492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93f3239d499'
down_revision = '7b64a5c3aec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('address', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'address')
    # ### end Alembic commands ###
